### ISSUE TITLE
Final changes for stage 1 completion

### ISSUE THREAD

**Issue by critzo** [throneless-tech/piecewise-old#14]
We have a small number of changes for the current deployment to be completed, coming out of external review:
* [x] Change this text on the first page:
  * **FROM**: If you’re one of the hundreds of thousands of North Carolinians struggling without good broadband, you can help out by answering a few short questions designed to measure the extent of the problem. Due to a myriad of inaccuracies in current broadband availability data collected by the federal government, the truth is unknown about who has good broadband and who doesn’t. This inaccurate data hurts communities who deserve a shot at broadband funding. Please act now by taking this scientific survey to help paint a clearer picture of our state’s broadband needs.
  * **TO:** If you’re one of the hundreds of thousands of North Carolinians struggling without good broadband Internet access, you can help out by answering a few short questions designed to measure the extent of the problem and provide evidence that more investment is essential. Due to many inaccuracies in current broadband availability data collected by the federal government, there is no accurate map showing where high-quality Internet access is available. When it comes to prices, neither the state nor federal government collect and share that information. Please act now by taking this scientific survey to help paint a clearer picture of our state’s broadband needs.
* [x] On the second "page" where location is prompted for, and the test begins, above the test, please add the two logos, and add this text below the logos:
  * Please answer these questions to the best of your ability - but feel free to skip a question if you do not know. It may help to find a recent bill for your Internet service provider before you start. We are most interested in what you are using to connect to the Internet in your home or office. 
* [x] Add paragraph:
  * You must click "Submit" at the end of the survey for your answers and test results to be recorded. You may also `[skip the survey](link to the bottom of the survey)` and only submit the speed test results.

**Comment by rudietuesdays** [comment]
@critzo updated on staging! https://staging.ilsr-nc.measuringbroadband.org/

**Comment by critzo** [comment]
@rae @jheretic I missed a couple of changes that were requested.

* [x] Please change "You may also skip the survey and only submit the speed test results. " 
TO: "You can can start the survey while the test is running or skip the survey and only submit the speed test results once the test completes."
* [x] When the test completes, at the top of the page where the test UI ran, please show the user this message: "Your results are shown on the bottom of the page." using the H3 heading size

**Comment by rudietuesdays** [comment]
@critzo updated on staging! https://staging.ilsr-nc.measuringbroadband.org/
