### ISSUE TITLE
UX related changes for stage 1

### ISSUE THREAD

**Issue by critzo** [throneless-tech/piecewise-old#5]
These items are mostly cosmetic and/or based on UX review by @critzo and ILSR:

Reference to "pages" below could be separate html pages, or single divs with different content shown to the site visitor. The user should not be prompted to share their location until they select the appropriate radio button.

* First "page" element order:
  * Move logos above the heading "North Carolina ... "
  * Heading
  * Current first paragraph
  * Last 2 sentences of current second paragraph
  * "Will you share your location?" text, add share/not share radio button, M-Lab consent checkbox, button to click to get started.

* Second "page":
  * Logos
  * Short link - "Skip the survey, take me to the speed test"
  * Heading
  * 1st three sentences of current second paragraph: "Please answer ... home or office"
  * survey
  * test

**Comment by critzo** [comment]
The in-progress work on this can be reviewed on https://staging.ilsr-nc.measuringbroadband.org/
After an initial UX review, the following updates need to be made:
* [x] After clicking "Take the Test", on Firefox at 100% zoom, the top line, "To put your speed test results..." is cut off. It's visible when I zoom to 90%. If we could test the CSS on both Firefox and Chrome that would be super.
* [x] The "Test your speed!" button is oddly formatted. Text bleeds over a grey vertical rectangle instead of a square button. 
* [x] Once I click Test your speed, I'm prompted to share my location, with the test window running behind it. The test isn't running at the moment, just the spinning circle, which may be expected at this point (related to the port issue?) 
* [x] Can we disable scrolling on the map or hide the map altogether when  we're viewing the survey/taking the test? If the cursor is on the map part and not the survey div, the map zooms in and out which is not expected.

Additionally, it was reported that the GCE firewall for the VM may have been blocking ports 8080 and 8443.
* [x] Add firewall rule(s) for the VM to allow these ports (DONE - @critzo )
* [x] Test and confirm the firewall rules have solved the issue

**Comment by rudietuesdays** [comment]
@critzo All these changes are now up on the staging instance! Please let me know if you see anything persisting. The UX should be a bit smoother now, thanks for coming up with this checklist.

https://staging.ilsr-nc.measuringbroadband.org/

**Comment by critzo** [comment]
I've confirmed that in Firefox, with Private Browsing enabled, and "share location temporarily" as the location privacy preference, that the test seems to run (spinning progress bar runs) but no location is shown on the page, and the test never completes.

In Chrome Incognito Mode, if location sharing is set to yes, the location still is shared, is visible, and the test runs and completes.

**Comment by critzo** [comment]
After our discussion today for completion of stage 1, I've outlined the to do list below. @rudietuesdays let me know if you have any questions about these items.

Description/order of items on initial page load:
* [x] ILSR & M-Lab Logos
* [x] Page Heading: "North Carolina Local Broadband Speed Test"
* [x] Paragraph 1 text: 
  * If you’re one of the hundreds of thousands of North Carolinians struggling without good broadband, you can help out by answering a few short questions designed to measure the extent of the problem. Due to a myriad of inaccuracies in current broadband availability data collected by the federal government, the truth is unknown about who has good broadband and who doesn’t. This inaccurate data hurts communities who deserve a shot at broadband funding. Please act now by taking this scientific survey to help paint a clearer picture of our state’s broadband needs. 
* [x] Paragraph 2 text:
  * To get the most accurate location data, we ask you to allow your browser to share your location. This is not essential but it is very helpful for creating more accurate maps. Depending on your browser, you'll see a window similar to the images below, requesting your consent to share your location. If you are using Private Browsing mode or Incognito mode, you may need to disable that preference for this website.
* [x] Small screen grabs of the location request from Firefox and Chrome
* [x] Take the test & View Results buttons
  * View results button action --> shows Take the Test & More Info buttons
  * More info button is a link, probably to the main ILSR sub-site. TBD, Chris M/Chris R will provide 
  * Take the Test button goes back to original view
* [ ] Take the Test link from original view initiates the user location consent box in the browser
* [ ] Survey form fields
* [ ] M-Lab consent check-box
* [ ] Test Your Speed button
* [x] Paragraph describing "Factors that might affect your test":
  * IN BOLD: Many factors may impact upload/download speed tests, at any given test period. This speed test measures how well your current connection works between your computer/device and the testing server itself – providing a general measure of how fast (or slow) your Internet connection is. This test doesn't necessarily mean that this is the bandwidth you should always expect between you and anywhere else. To ensure the most accurate test results:
  * Ordered list:
    * If possible, connect your computer to your ISP modem or router directly with an Ethernet cord.
    Minimize the "noise" during an Internet speed test, which is what the several tips above help you do, certainly contributes to a more accurate speed test result.
    * Test periodically at different times of the day can help show your connection's speed trends over time.
  * If you are seeing results that differ from other speed tests, the M-Lab [FAQ](https://www.measurementlab.net/faq/#why-are-my-m-lab-results-different-from-other-speed-tests) provides helpful information to help understand why.
  * The map shows aggregate test results from all accumulated M-Lab tests. Any test taken with an M-Lab testing application (i.e. the speed test within Google search results) will be presented on the map.
  * Test results from this website will not be immediately available on the map, but will be shown as a separate map layer once enough new survey data is collected.
* [ ] Action when Test Your Speed button is clicked:
  * speed test runs
  * survey and test data are submitted to the database

**Comment by rudietuesdays** [comment]
Hi @critzo and @laiyi-ohlsen ! I pushed a number of updates to the staging site, but had questions on the boxes that I didn't check off.

From the list, I couldn't tell if the survey page should now be on the first page, or if it should still show upon clicking "Take the test." Could you verify if all this content should be on the first page, or if it should be broken up more?

You can see the latest updates on staging: https://staging.ilsr-nc.measuringbroadband.org/

Thanks!

**Comment by critzo** [comment]
Hi @rudietuesdays ! Thanks for this update. 

Good question, and I think this could have been clearer, or we neglected to share part of the discussion prior to your joining the call on Fri.

Since we're adding the location screenshots and telling them about that on the first "page", we can remove the second "page" information and just prompt the user for their location, then start the test when "Take the test" is clicked.

* [x] Add an `<h2>` heading before the second paragraph: "Sharing your Location"-- this is a new item I think will help the reader
* [x] Please move the location radio preference and M-Lab consent checkbox to just above the "Take the test" button, as indicated in this mockup:

![move-consent](https://user-images.githubusercontent.com/4633345/74156530-7ec9c300-4be4-11ea-9204-5683a1eea83b.png)

* [x] Instead of being below the checkbox, could the "I agree to the M-Lab.. " text be aligned with the checkbox, and wrap onto the line below?
* [x] "Take the Test" button should do what the "Test your speed!" button does currently- prompts user for location then runs the test. 
* [x] remove text "Factors that might affect your test" section on what is currently below "Test your speed!" I think this is better suited on an FAQ, and we could either ask Chris M to add it to his site, or we could add it to the M-Lab FAQ and link to it.
* [x] Remove the "Skip the survey" button. We may add that back in later in stage 2
* [x] Confirm that the submit results button is working and data is being posted to the database

**Comment by critzo** [comment]
Additional review of updates posted ~4:30pm EST 2/11:
* [x] View Results button hides everything and doesn't let you get back. Remove View Results button until we have the map basetiles and local map layer working
* Test runs in a div separate from the survey, which covers up the survey box. The "X" and "..." links to show/hide the test boxis ok, but took me a second to even see it. 
  * [x] Can we put the test at the top of the survey in the same div?
  * So the user clicks their location choice radio, and the M-Lab consent checkbox, then "Take the Test"
  * User is prompted to share their location, and the test starts running
  * No show/hide links, it's just running at the top of the survey. They scroll down to take the survey. 
  * User submits the results at the end of the survey.
* I like that you added some text near the submit button while the test is running: "Note: Survey cannot be submitted until after speed test is complete." That is removed when it has completed. 
  * [x] Can you replace that text with the test results (non-editable) at the bottom near the Submit button when the test completes?
* [x] After a user clicks "Submit" to send the results in, they should be shown their Test results and the Thank you message with sharing options.

**Comment by rudietuesdays** [comment]
@critzo thanks, updated on the staging site! https://staging.ilsr-nc.measuringbroadband.org/

**Comment by critzo** [comment]
Calling this one done.

**Comment by laiyi-ohlsen** [comment]
Wooooo thanks @critzo @rudietuesdays for this push!
